#----------------------------------------------------------------------------
# Copyright (c) 2021 Ando Ki.
# All rights are reserved by Ando Ki.
#----------------------------------------------------------------------------
# Makefile
#------------------------------------------------------------------------
SHELL	= /bin/sh
#------------------------------------------------------------------------
IPC_LIB	= cosim_ipc
SRCS	= cosim_ipc.c
OBJS	= $(SRCS:.c=.o)
#------------------------------------------------------------------------
OBJECTDIR   = obj
DUMMY      := $(shell [ -d $(OBJECTDIR) ] || mkdir $(OBJECTDIR) )
#------------------------------------------------------------------------
PLATFORM    = $(shell uname -s | tr '[:upper:]' '[:lower:]')
MACHINE     = $(shell uname -m)
#------------------------------------------------------------------------
vpath %.h	src
vpath %.c	src
#------------------------------------------------------------------------
CC         = gcc
CC_VERSION = $(shell gcc -dumpversion)
#------------------------------------------------------------------------
INCDIRS     = -Isrc
C_USER_DEFS =
CFLAGS      = -g -O0 -Werror $(C_USER_DEFS) $(INCDIRS)
LDFLAGS     = -O0 -Bsymbolic -shared
LDLIBS      =
#------------------------------------------------------------------------
CFLAGS      += -fPIC
#------------------------------------------------------------------------
.PHONY: all
all: pre lib$(IPC_LIB).a

pre:
	if [ -f compile.log ]; then /bin/rm -f compile.log; fi
#------------------------------------------------------------------------
$(OBJECTDIR)/%.o: %.c
	$(CC) -c $(CFLAGS) $< -o $@

#------------------------------------------------------------------------
lib$(IPC_LIB).a: $(addprefix $(OBJECTDIR)/,$(OBJS))
	ar crUu $@ $(addprefix $(OBJECTDIR)/,$(OBJS))
	ranlib $@
	if [ -f $@ ]; then\
		if [ ! -d $(PLATFORM)/$(CC)/$(CC_VERSION) ]; then mkdir -p $(PLATFORM)/$(CC)/$(CC_VERSION); fi;\
		cp $@ $(PLATFORM)/$(CC)/$(CC_VERSION);\
	fi

#------------------------------------------------------------------------
.PHONY: clean
clean:
	rm -rf $(OBJECTDIR)
	rm -f  *.log
	rm -f  *.o
	rm -f *stackdump
	rm -f *.exe.core
	rm -f transcript compile.log

.PHONY: cleanup clobber
cleanup clobber: clean
	rm -f $(IPC_LIB).dll lib$(IPC_LIB).a lib$(IPC_LIB).so

.PHONY: cleanupall distclean
cleanupall distclean: cleanup
	/bin/rm -rf $(PLATFORM)

#----------------------------------------------------------------------------
# Revision history
#
# 2021.07.01: Started by Ando Ki (andoki@gmail.com)
#----------------------------------------------------------------------------
